# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Esword"
email = "jyj349559953@qq.com"
link = "https://github.com/Esword618"
